[project]
name = "marvl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib==3.10.0",
    "netcdf4==1.7.4",
    "numpy==2.3.0",
    "pandas==2.2.3",
    "xarray==2026.1.0",
]

[dependency-groups]
dev = [
    "ruff>=0.15.0",
]
[tool.ruff]
lint.extend-select = ["I"]
line-length = 79
